# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: bootshop # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7

# you can overwrite defaults here
#defaults:
  stage: dev
  region: eu-west-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: greet
          method: get

  listProducts:
    handler: product.list
    events:
      - http:
          path: product/list
          method: get

  addProducts:
    handler: product.add
    events:
      - http:
          path: product/add
          method: put

  listCart:
    handler: cart.list
    events:
      - http:
          path: cart/list
          method: get

  addToCart:
    handler: cart.add
    events:
      - http:
          path: cart/add
          method: put

  clearCart:
    handler: cart.clear
    events:
      - http:
          path: cart/clear
          method: get

  listOrders:
    handler: order.list
    events:
      - http:
          path: order/list
          method: get

  addOrder:
    handler: order.add
    events:
      - http:
          path: order/add
          method: put
#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
